### ISSUE TITLE
simplyValidate isn't properly integrated

### ISSUE THREAD

**Issue by natebecker11** [CWRU-Ilvermorny/My-Celebrity-Horoscope#20]
Dustin's simplyValidate.js isn't working properly. Investigate possibly hosting locally?

`GET https://cdn.jsdelivr.net/npm/simply_valid@4.0.1/dist/simplyValid.js 404 ()
index.html:1 Refused to execute script from 'https://cdn.jsdelivr.net/npm/simply_valid@4.0.1/dist/simplyValid.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

**Comment by Prerry2** [comment]
The link was broken, and is now replaced with a working link.
